In [27]:
import numpy as np

In [2]:
# bilangan distribusi uniform(0-1)
np.random.rand(7)

array([0.34141005, 0.5586679 , 0.24428358, 0.72568403, 0.73372801,
       0.64433411, 0.07866976])

In [4]:
# bilangan distribusi matrix uniform(0-1) 2 dimensi
np.random.rand(5,4)

array([[0.04429856, 0.71851013, 0.83354661, 0.40266336],
       [0.13244793, 0.97323418, 0.38092444, 0.17765511],
       [0.70517692, 0.45807992, 0.26619074, 0.90299221],
       [0.70734724, 0.5216124 , 0.18299916, 0.57890007],
       [0.4647825 , 0.73150842, 0.39692768, 0.30040039]])

In [6]:
#bilangan distribusi normal (gaussian)
np.random.randn(10)

array([-1.66237729,  0.38983056, -1.02088049,  0.17570313, -1.84487539,
       -1.25455009, -0.3580392 ,  0.37449628,  1.51715824,  0.0150023 ])

In [7]:
#bilangan distribusi normal (gaussian) matrix 2 dimensi
np.random.rand(4,4)

array([[0.24698561, 0.56593222, 0.50590975, 0.95977175],
       [0.18303481, 0.65228401, 0.79698786, 0.99799383],
       [0.83939288, 0.06866657, 0.6125086 , 0.42570853],
       [0.21756405, 0.30778907, 0.18255061, 0.18249019]])

In [3]:
from numpy.random import randn, randint ,rand

In [10]:
randn(6,2)

array([[ 0.06942267, -2.0559129 ],
       [ 0.1381356 ,  0.80460507],
       [ 1.67474136, -0.72275163],
       [ 1.43858939, -0.40997207],
       [-0.73549338, -2.00200904],
       [ 0.66916776, -0.42267172]])

In [12]:
randint(0,10)

5

In [13]:
randint(0,10,5)

array([7, 7, 2, 5, 6])

In [14]:
bilangan = randint(0,100,20)

In [15]:
bilangan

array([34, 80, 18,  6, 56, 83, 12, 75, 11,  6, 46, 97, 79, 55, 53, 12, 58,
       14,  7, 13])

In [16]:
bilangan.reshape(4,5)

array([[34, 80, 18,  6, 56],
       [83, 12, 75, 11,  6],
       [46, 97, 79, 55, 53],
       [12, 58, 14,  7, 13]])

In [19]:
randint(0,3,5)

array([2, 0, 0, 1, 0])

In [4]:
coba = randint(0, 10, 20).reshape(4,5)

In [5]:
coba

array([[7, 3, 4, 9, 9],
       [8, 3, 4, 5, 2],
       [0, 1, 2, 9, 6],
       [1, 8, 7, 3, 4]])

In [6]:
coba = coba.reshape(2,10)

In [7]:
coba

array([[7, 3, 4, 9, 9, 8, 3, 4, 5, 2],
       [0, 1, 2, 9, 6, 1, 8, 7, 3, 4]])

In [8]:
coba1d = randint(0,100,20)

In [9]:
coba2d = randint(0,100,20).reshape(4,5)

In [10]:
coba1d

array([25, 49, 16, 81, 92, 91, 77, 42, 65, 50, 47, 10, 19, 68, 68, 34, 13,
       73,  8, 92])

In [11]:
coba2d

array([[90,  6, 60,  6, 37],
       [31,  6, 29, 25, 42],
       [ 7, 57, 37, 27, 20],
       [ 3, 92, 31, 70, 79]])

In [13]:
coba1d.max()

92

In [14]:
coba2d.max()

92

In [15]:
coba1d.min()

8

In [16]:
coba2d.min()

3

In [18]:
coba1d.argmax()

4

In [19]:
coba2d.argmax()

16

In [20]:
coba1d.argmin()

18

In [21]:
coba2d.argmin()

15

In [23]:
coba1d.shape

(20,)

In [24]:
coba2d.shape

(4, 5)

In [25]:
coba1d.dtype

dtype('int32')

In [28]:
coba = np.arange(0,11)

In [29]:
coba[0]

0

In [30]:
coba[5:]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
coba2 = coba.copy()

In [37]:
coba2

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [38]:
coba2[:] = 10

In [39]:
coba2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [40]:
coba

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [41]:
bil2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
bil2d[0][1]

2

In [44]:
bil2d[2,2]

9

In [46]:
bil2d[1:2, 1:]

array([[5, 6]])

In [47]:
# Slicing dengan boolean numpy

In [55]:
bila = np.arange(1,10)

In [56]:
bila

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
angkaT = bila>5

In [51]:
angkaT

array([False, False, False, False, False,  True,  True,  True,  True])

In [53]:
bila = bila[angkaT]

In [59]:
bila = bila[bila>5]

In [60]:
bila

array([6, 7, 8, 9])