In [1]:
import numpy as np

In [2]:
angka = [1,2,3]

In [3]:
angkanp = np.array(angka)

In [4]:
angkanp

array([1, 2, 3])

In [5]:
angka*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
angkanp * 3

array([3, 6, 9])

In [7]:
versilist =[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
versinumpy = np.array(versilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

identify matrix

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])